---
anchors: #x, y, z are measured in mm
    -       # should be at origin point
        anchor_id: 0x6a18
        px: 0
        py: 0
        pz: 1784
    -       # defines x axis and y should be 0
        anchor_id: 0x6a27
        px: 6800
        py: 0
        pz: 1833
    -   # defines the direction of y so y should be positive
        anchor_id: 0x670c
        px: -400
        py: 1780
        pz: 1500
    -
        anchor_id: 0x6a24
        px: 14000
        py: -8700
        pz: 670
    -
        anchor_id: 0x6a15
        px: 6800
        py: -8700
        pz: 1735
    -
        anchor_id: 0x6a38
        px: -2800
        py: -5620
        pz: 400
    -
        anchor_id: 0x6a41
        px: 20600
        py: -5025
        pz: 1200
    -
        anchor_id: 0x6a6e
        px: 20600
        py: -10795
        pz: 1900
    -
        anchor_id: 0x6a79
        px: -400
        py: -9525
        pz: 2300
    -
        anchor_id: 0x6a17
        px: -2800
        py: -6140
        pz: 1700
    -
        anchor_id: 0x6a2f
        px: -9300
        py: -9025
        pz: 2500
    -
        anchor_id: 0x6a05
        px: -8000
        py: -14835
        pz: 1632
    -
        anchor_id: 0x6a5d
        px: -8800
        py: 490
        pz: 500
    -
        anchor_id: 0x6a26
        px: -9800
        py: 5380
        pz: 2000
    -
        anchor_id: 0x6a2c
        px: 0
        py: 0
        pz: 500
    -
        anchor_id: 0x6a20
        px: 3820
        py: -2095
        pz: 2703
